name: Fetch italictype data

on:
schedule:
  - cron: "0 */12 * * *"

jobs:
  fetch-data:
    env: 
      IT_USER: ${{ secrets.ITALIC_TYPE_USERNAME }}
      IT_PASSWORD: ${{ secrets.ITALIC_TYPE_PASSWORD }}
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: cd ./backend
    - run: npm ci
    - run: node update.js
    - run: cd ..
    - name: Commit updated public_data.json
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "update public_data.json"
        add: "./src/assets/public_data.json"
        signoff: true
